### ISSUE TITLE
v0.3.0 roadmap

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/djangocms-comments#3]
**TODO**
- [ ] Disable anonymous/authenticated users.
- [ ] Refactor Comments model to Abstract model.
- [ ] Moderate comments in front.
- [ ] reCaptcha support.
